 
base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  source: given_data/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89
      # alpha: 0.56
      # l1_ratio: 0.79
      # alpha: 0.9
      # l1_ratio: 0.82
#model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

model_dir: prediction_service\model\model.joblib
schema_dir: prediction_service\schema.json


mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://localhost:1234


